SkillsFundingAgency/das-assessor-service

- src/SFA.DAS.AssessorService.Web/Controllers/AccountController.cs
So it turns out the error on the AT site is because we're not receiving an email address back from claims.  This PR is to output to logs ALL of the claims we're receiving so we can see what's being returned to us.
> Logging claims received

- src/SFA.DAS.AssessorService.Application.Api/appsettings.Development.json
- src/SFA.DAS.AssessorService.Settings/WebConfiguration.cs
- src/SFA.DAS.AssessorService.Web.UnitTests/AccountControllerTests/Given_I_have_signed_in.cs
- src/SFA.DAS.AssessorService.Web.UnitTests/AccountControllerTests/Given_I_request_Sign_In.cs
- src/SFA.DAS.AssessorService.Web.UnitTests/SearchControllerTests/SearchControllerTestBase.cs
- src/SFA.DAS.AssessorService.Web/Controllers/AccountController.cs
- src/SFA.DAS.AssessorService.Web/Controllers/CertificateAddressController.cs
- src/SFA.DAS.AssessorService.Web/Controllers/CertificateBaseController.cs
- src/SFA.DAS.AssessorService.Web/Controllers/CertificateCheckController.cs
- src/SFA.DAS.AssessorService.Web/Controllers/CertificateConfirmationController.cs
- src/SFA.DAS.AssessorService.Web/Controllers/CertificateController.cs
- src/SFA.DAS.AssessorService.Web/Controllers/CertificateDateController.cs
- src/SFA.DAS.AssessorService.Web/Controllers/CertificateDeclarationController.cs
- src/SFA.DAS.AssessorService.Web/Controllers/CertificateGradeController.cs
- src/SFA.DAS.AssessorService.Web/Controllers/CertificateOptionController.cs
- src/SFA.DAS.AssessorService.Web/Controllers/SearchController.cs
- src/SFA.DAS.AssessorService.Web/Infrastructure/CheckSessionFilter.cs
- src/SFA.DAS.AssessorService.Web/Infrastructure/ISessionService.cs
- src/SFA.DAS.AssessorService.Web/SFA.DAS.AssessorService.Web.csproj
- src/SFA.DAS.AssessorService.Web/Startup.cs
- src/SFA.DAS.AssessorService.Web/Views/Shared/_Layout.cshtml
- src/SFA.DAS.AssessorService.Web/appsettings.Development.json
- src/SFA.DAS.AssessorService.Web/appsettings.json
New Redis Session connection string setting is no longer Required so will not crash while setting not present.
All session is now accessed through SessionService that prepends the environment name onto session keys as the Redis instance is shared across environments.
> On 457 ensure session keys scoped to env

- src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Search/When_assessmentorgs_api_returns_non_int_stdcode.cs
- src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Search/When_certificate_already_submitted_for_learner.cs
- src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Search/When_certificate_does_not_exist_for_learner.cs
- src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Search/When_learner_has_two_standards_with_one_certificate.cs
- src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Search/When_returned_learners_do_not_match_users_epaorgid.cs
- src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Search/When_returned_learners_match_users_epaorgid.cs
- src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Search/When_search_contains_any_type_of_special_character.cs
- src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Search/When_standard_exists_for_learner.cs
- src/SFA.DAS.AssessorService.Application/Handlers/Search/SearchHandler.cs
- src/SFA.DAS.AssessorService.Application/Interfaces/IIlrRepository.cs
- src/SFA.DAS.AssessorService.Application/Interfaces/SearchRequest.cs
- src/SFA.DAS.AssessorService.Data/IlrRepository.cs
Learner search now only queries db for lastname & uln.  Following that only checks the user's epoa's allowed standards if the ilr epaoid is different to their own.
> Change to logic of learner search

- LoadCertificateData.sql
Covers th following from the ticket:
1) To include the "Full Name" field on the Spreadsheet as "FullName" in the CertificateData json object, for all previously imported and new Certificates.
2) Where the ULN does not match to a current ILR record, and hence cannot lookup GivenNames and FamilyName, to decompose the Full Name as RIGHT Word (inclusive of Hyphens) = FamilyName, remainder = GivenNames.
3) Where the ULN is 9999999999 (which it should not be!) do not to attempt to match to ILR record 
4) Include all Certificates, including where Source = "Other" and not just Source ="ILR" - there may be an ILR record for these (as "Other" may / may not be correct); Step 2 will handle the completion of the name fields.
5) Also, note that Provider UKPRN is not always given for "Other", so should …
> On 553 may18 cert import changes

- src/SFA.DAS.AssessorService.Web.Staff/Views/Dashboard/Index.cshtml
One extra closing bracket was the problem.  The code that decides whether to show the section or not was looking for "EPA)" instead of "EPA".
> AssessmentDeliveryTeam reports access denied fix

- src/SFA.DAS.AssessorService.Application.Api.External/Controllers/CertificateController.cs
Hopefully the last PR. The WAV heavily restricts requests and thus we have to explicitly state what MIME types we consume & produce
> On 1195 external api sandbox updates

- src/SFA.DAS.AssessorService.EpaoImporter/SFA.DAS.AssessorService.EpaoImporter.csproj
Updated NuGet references as the build pipeline is referencing a package that is no longer available
> Fix broken epao importer

- src/SFA.DAS.AssessorService.Api.Types/Models/Roatp/CreateOrganisationRequest.cs
- src/SFA.DAS.AssessorService.Api.Types/Models/Roatp/DuplicateUKPRNCheckRequest.cs
- src/SFA.DAS.AssessorService.Api.Types/Models/Roatp/Organisation.cs
- src/SFA.DAS.AssessorService.Web.Staff/Controllers/Roatp/AddRoatpOrganisationController.cs
This prevents valid UKPRN values from being rejected by WAF parsing rules
> Change UKPRN field in RoATP API requests to string

- azure/sandbox-template.json
The following amendments have been made to the sandbox-template.json file:
- There are two App Service deployments (internal and external) which were referencing the one Certificate resource deployment to get the thumbprint output. This worked when using the wildcard certificate, however in order to support two different custom hostnames in PROD I have amended the template to include two Certificate resource deployments. The certificateName parameter has been removed and replaced with two additional parameters; externalApiSandboxAppServiceCertificateName and internalApiSandboxAppServiceCertificateName.
- Added a new Storage Account resource deployment to create a new storage account for the new sandbox function app. A new parameter has been added sandboxFunctionAppStorageAccountName.
- …
> Amendments to the sandbox-template.json

- azure/sandbox-template.json
Removed aspLocation parameter from the sandbox-app-service-plan resource deployment. This is because it was referencing the location of the resource group which returns "westeurope" however the building block template only allows the value "West Europe". The pipeline logs would return the following:
`Deployment template validation failed: 'The provided value 'westeurope' for the template parameter 'aspLocation' at line '8' and column '20' is not valid. The parameter value is not part of the allowed value(s): 'North Europe,West Europe'.'.",`
> Removed aspLocation parameter from the sandbox-app-service-plan resource deployment.

- azure/sandbox-template.json
The resource deployments of the web and function apps are dependent on the sandbox-app-service-plan resource deployment, however the deployment fails due to the aspInstances parameter being type string rather than int. The building block template app-service-plan.json requires a int type for the aspInstances parameter. The deployment fails with: 
> "Deployment template validation failed: 'The provided value for the template parameter 'aspInstances' at line '32' and column '21' is not valid.'."
> Changed aspInstances parameter type from string to int to match building block template.

- azure/sandbox-template.json
The sandbox API web app requires connectivity to the sandbox SQL database das-pp-ass-sbox-db. In order to do this the sandbox-template.json file has been amended with the following:
- Added sandboxSqlDbConnectionString parameter to sandbox-template.json.
- sandboxSqlDbConnectionString parameter added to the appServiceConnectionStrings section of the internal API web app resource deployment section.
> Added sandboxSqlDbConnectionString to the Internal Sandbox API Web App.

- azure/sandbox-template.json
The Assessors Sandbox API function app in PREPROD was targeting v1 run time but needs to be v2. The following errors appear when viewing the function app in the Azure Portal:
- `Error: The function type name is invalid.`
- `Error: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.`
> Changed FUNCTIONS_EXTENSION_VERSION to ~2

- src/SFA.DAS.AssessorService.Database/SFA.DAS.AssessorService.Database.sqlproj
- src/SFA.DAS.AssessorService.Database/StoredProcedures/Delete_Certificate.sql
This stored proc is ONLY for manual execution (by DevOps), to ensure that a Certificate is correctly 'soft' deleted
> On 2326 delete certificate stored proc

- azure/template.json
For DASD-6869 the ARM template `azure/template.json` has been updated with the following to ensure the appropriate certificate from the shared key vault is deployed into the shared resource group:
- Added `keyVaultResourceGroupName` and `keyVaultName` parameters.
- Added new resource deployment `api-app-service-certificate` to deploy the appropriate key vault certificate based on parameter `apiKeyvaultCertificateName` to the shared app service resource group.
- Amended the `certificateThumbprint` setting for the internal API App Service deployment to reference the new `api-app-service-certificate` deployment. 
- Added `dependsOn` to the internal API App Service deployment with a dependency on the `api-app-service-certificate` resource deployment.
> Updated the Internal API App Service to use a Certificate Resource Deployment

- src/SFA.DAS.AssessorService.Web/Controllers/Apply/ApplicationController.cs
- src/SFA.DAS.AssessorService.Web/Views/Application/Pages/Index.cshtml
- src/SFA.DAS.AssessorService.Web/Views/Application/Pages/MultipleAnswers.cshtml
This is a new branch as I messed up the original; when testing the first version it turned out that __redirectAction is hard coded in the QnA so this version will just move the double underscore form variables which can be moved into route variable instead.
> CON-1612 Renamed __formAction and moved other double underscore form variables into route variables.

- src/SFA.DAS.AssessorService.Web/Controllers/AccountController.cs
The session is setup for one hour. Once the session expires the authentication cookies are deleted automatically. At this point if user tries to signout, the login service throws a fit due to absence of the session identifier. 
To mitigate this, we call signout only if the user is still authenticated otherwise we just navigate back to home page.
> QUAL-51 Fixes error on signout after session expired

- src/SFA.DAS.AssessorService.Api.Types/Models/ExternalApi/Certificates/BatchCertificateRequest.cs
- src/SFA.DAS.AssessorService.Application.Api.UnitTests/Validators/ExternalApi/Certificates/CreateBatchCertificateRequestValidator/WhenCompletionStatusIsInvalid.cs
- src/SFA.DAS.AssessorService.Application.Api.UnitTests/Validators/ExternalApi/Epas/CreateBatchEpaRequestValidator/WhenLearnerHasTemporarilyWithdrawnFromTheILR.cs
- src/SFA.DAS.AssessorService.Application.Api.UnitTests/Validators/ExternalApi/Epas/CreateBatchEpaRequestValidator/WhenLearnerHasWithdrawnFromTheILR.cs
- src/SFA.DAS.AssessorService.Application.Api.UnitTests/Validators/ExternalApi/ExternalApiValidatorsTestBase.cs
- src/SFA.DAS.AssessorService.Application.Api/Controllers/ExternalApi/CertificateBatchController.cs
- src/SFA.DAS.AssessorService.Application.Api/Validators/ExternalApi/Certificates/CreateBatchCertificateRequestValidator.cs
- src/SFA.DAS.AssessorService.Application.Api/Validators/ExternalApi/Epas/BatchEpaRequestValidator.cs
- src/SFA.DAS.AssessorService.Application/Handlers/Staff/GetLearnerDetailHandler.cs
- src/SFA.DAS.AssessorService.Data/IlrRepository.cs
- src/SFA.DAS.AssessorService.Domain/Consts/CompletionStatus.cs
I have added two new validation rules to the CreateBatchCertificate request validator that will check if the learners completion status is not withdrawn or temporarily withdrawn
> CON-2418 Adds additional validation of completion status to the api

- src/SFA.DAS.AssessorService.Application/Handlers/Certificates/GetCertificatesHistoryHandler.cs
- src/SFA.DAS.AssessorService.Application/Handlers/Certificates/GetCertificatesToBeApprovedHandler.cs
- src/SFA.DAS.AssessorService.Web/Validators/CertificateUkprnViewModelValidator.cs
Previous implementation of finding provider from FATv1 relied on an EntityNotFoundException being thrown when the provider didn't exist. Added in logic so that now if the returned item is null then this exception is thrown
> FAT2-438 Provider not found bug

- src/SFA.DAS.AssessorService.Api.Types/Models/Standards/StandardOptions.cs
- src/SFA.DAS.AssessorService.Application.Api.External/Models/Response/Standards/StandardOptions.cs
- src/SFA.DAS.AssessorService.Application.Api.UnitTests/Services/StandardServiceTests.cs
- src/SFA.DAS.AssessorService.Application.Api/Services/StandardService.cs
The external API should match the version field to the IFATE API, hence I am converting it  in the internal API. Currently the format in IFATE API is matching to ("#.0"). If this ever changes our code will have to change as well.
> SV-535 Fix version to be a string in external api response

- src/SFA.DAS.AssessorService.Application.Api.External.UnitTests/Controllers/StandardsControllerTests.cs
- src/SFA.DAS.AssessorService.Application.Api.External.UnitTests/SFA.DAS.AssessorService.Application.Api.External.UnitTests.csproj
- src/SFA.DAS.AssessorService.Application.Api.External/Controllers/StandardsController.cs
- src/SFA.DAS.AssessorService.Application.Api.External/Infrastructure/ApiClient.cs
- src/SFA.DAS.AssessorService.Application.Api.External/Infrastructure/IApiClient.cs
- src/SFA.DAS.AssessorService.Application.Api.External/SwaggerHelpers/Examples/GetStandardVersionOptionsResponseExample.cs
- src/SFA.DAS.AssessorService.Application.Api.External/appsettings.json
- src/SFA.DAS.AssessorService.Application.Api.UnitTests/Services/StandardServiceTests.cs
- src/SFA.DAS.AssessorService.Application.Api/Controllers/StandardServiceController.cs
- src/SFA.DAS.AssessorService.Application.Api/Services/StandardService.cs
- src/SFA.DAS.AssessorService.Application/Interfaces/IStandardRepository.cs
- src/SFA.DAS.AssessorService.Application/Interfaces/IStandardService.cs
- src/SFA.DAS.AssessorService.Data.IntegrationTests/Handlers/StandardsHandler.cs
- src/SFA.DAS.AssessorService.Data.IntegrationTests/Models/StandardModel.cs
- src/SFA.DAS.AssessorService.Data.IntegrationTests/StandardsGetTests.cs
- src/SFA.DAS.AssessorService.Data/StandardRepository.cs
- src/SFA.DAS.AssessorService.sln
I've created the get standard version endpoint and added a unit test project for the external API.
To get the StandardUId I have found all standards with the given standard reference and then tried to match with the given version. I thought this was better than querying based on the standard reference and version as the original query could be reused or it might help if we need error handling that says "version x does not exist for that standard".
Once we know the StandardUId I could use the existing outer API method
> SV-537 get standard version options

- src/SFA.DAS.AssessorService.Web/Views/Certificate/Check.cshtml
If there are any rows on the table with actions then every other row must have it's own `<dd class="govuk-summary-list__actions"></dd>` even if it is empty for the table to display lines and change link position correctly
> SV-613 change link out of line

- src/SFA.DAS.AssessorService.Web.UnitTests/CertificateTests/CertificateVersionControllerTests.cs
- src/SFA.DAS.AssessorService.Web/Controllers/CertificateVersionController.cs
- src/SFA.DAS.AssessorService.Web/ViewModels/Certificate/CertificateDateViewModel.cs
- src/SFA.DAS.AssessorService.Web/Views/Certificate/Date.cshtml
Resolves issue with Certificate Date Model so that the fail date is shown on the date page.
Resolves bug with options whereby you can't change version and redirect back to check without having set an option.
( can still press back but this will be resolved via submit check page validation )
> SV-607 Fail Date Not Being Pre-Populated

- src/SFA.DAS.AssessorService.Database/PostDeploymentScripts/EPAO_Migration_Part0_Patch.sql
- src/SFA.DAS.AssessorService.Database/SFA.DAS.AssessorService.Database.sqlproj
This fixes the use of "Version":"" rather than "version":"" in CertificateData for the histocial certificate records.
> SV-635 Patch for "version" data field in CertificateData

- src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Certificates/StartCertificateHandlerTests/When_called_and_certificate_previously_recorded_a_fail.cs
- src/SFA.DAS.AssessorService.Application/Handlers/Staff/StartCertificateHandler.cs
- src/SFA.DAS.AssessorService.Domain/Consts/CertificateActions.cs
We were previously unable to leave and resume recording a pass from a previously failed apprenticeship as when Starting the new certificate if a failed certificate was found it would be returned and we were allowed to overwrite it. However, the status of the certificate was still Submitted, so when we changed the grade to a pass and left the search found a passing, submitted certificate and did not allow changes to be made.
I have added a check when starting a new certificate so that if the result is Submitted + Fail then set status to draft and log that it is recording a retake. Submitted is important so draft fails aren't logged as retakes.
> SV-511 allow resuming when recording a retake after fail

- src/SFA.DAS.AssessorService.Web.UnitTests/CertificateTests/CertificateCheckControllerTests.cs
- src/SFA.DAS.AssessorService.Web.UnitTests/Validators/CertificateCheckViewModelValidatorTests.cs
- src/SFA.DAS.AssessorService.Web/Controllers/CertificateCheckController.cs
- src/SFA.DAS.AssessorService.Web/Resources/Validators/CertificateCheckViewModelValidator.Designer.cs
- src/SFA.DAS.AssessorService.Web/Resources/Validators/CertificateCheckViewModelValidator.resx
- src/SFA.DAS.AssessorService.Web/Validators/CertificateCheckViewModelValidator.cs
- src/SFA.DAS.AssessorService.Web/Views/Certificate/Check.cshtml
I've added validation for Grade, Version and Achievement date. 
The existing unit tests for the CertificateCheckController were getting complicated because it was loading different certificates for each scenario and used a concrete validator. I've now changed the controller tests to use a mocked validator to check if the redirection and update API calls are correct if the view model is valid or not and then added a set of tests on the validator itself.
> SV-619 validate all fields on check page on submit

- src/SFA.DAS.AssessorService.Api.Types/Models/Standards/StandardVersionOption.cs
- src/SFA.DAS.AssessorService.Application.Api.External.UnitTests/Controllers/StandardsControllerTests.cs
- src/SFA.DAS.AssessorService.Application.Api.External/Controllers/CertificateController.cs
- src/SFA.DAS.AssessorService.Application.Api.External/Controllers/StandardsController.cs
- src/SFA.DAS.AssessorService.Application.Api.External/Infrastructure/ApiClient.cs
- src/SFA.DAS.AssessorService.Application.Api.External/Infrastructure/IApiClient.cs
- src/SFA.DAS.AssessorService.Application.Api.External/SwaggerHelpers/Examples/GetOptionsForAllStandardResponseExample.cs
- src/SFA.DAS.AssessorService.Application.Api.External/SwaggerHelpers/Examples/GetOptionsForStandardResponseExample.cs
- src/SFA.DAS.AssessorService.Application.Api.External/appsettings.json
- src/SFA.DAS.AssessorService.Application.Api.UnitTests/Services/StandardServiceTests.cs
- src/SFA.DAS.AssessorService.Application.Api/Controllers/StandardVersionController.cs
- src/SFA.DAS.AssessorService.Application.Api/Services/StandardService.cs
- src/SFA.DAS.AssessorService.Application/Interfaces/IStandardRepository.cs
- src/SFA.DAS.AssessorService.Application/Interfaces/IStandardService.cs
- src/SFA.DAS.AssessorService.Data.IntegrationTests/GetStandardOptionsTests.cs
- src/SFA.DAS.AssessorService.Data.IntegrationTests/Handlers/StandardOptionsHandler.cs
- src/SFA.DAS.AssessorService.Data.IntegrationTests/Handlers/StandardsHandler.cs
- src/SFA.DAS.AssessorService.Data.IntegrationTests/Models/StandardModel.cs
- src/SFA.DAS.AssessorService.Data.IntegrationTests/Models/StandardOptionModel.cs
- src/SFA.DAS.AssessorService.Data/StandardRepository.cs
I've added a new GetStandardOptionsForLatestStandardVersions to the internal API with a specific query, repository + service methods to return only the latest standard versions which have options. 
The External API was changed to call the new internal API method as GET ALL versions is not required for the external API but GET ALL is still used in the internal API
> SV-507 external api get options

- azure/sandbox-template.json
Removed dependsOn resource group deployment in sandbox-template.json
- Resource group is not deployed in sandbox-template.json so there should not be dependsOn for the resource group
> Removed dependsOn resource group deployment in sandbox-template.json

- src/SFA.DAS.AssessorService.Application.Api.External/AutoMapperProfiles/CertificateDataProfile.cs
- src/SFA.DAS.AssessorService.Application.Api.External/AutoMapperProfiles/GetBatchLearnerResponseProfile.cs
I've reused the DropMilliseconds extension method to format get learner data and have also applied it to the Get Certificate Achievement date as the same bug would apply there too
> SV-836 drop milliseconds from get learner data

- src/SFA.DAS.AssessorService.Database/PostDeploymentScripts/EPAO_Migration_Part4_Apply.sql
This addition to post-deployment script will add the "Versions" data array to Apply.ApplyData."Apply" for all historical Applications (for standard or standard withdrawal), matching the standard versions that pre-existed at the time the Application was Approved (if Approved date set), or when last actioned by Admin users, or when created if the application is still in progress.
> SV-879 patch apply for versioning

- .github/CODEOWNERS
- Added das-sql-permissions team to CODEOWNERS for PostDeploymentScripts folder
- Removed named users as file not used previously
> Added das-sql-permissions team to CODEOWNERS for PostDeploymentScripts folder

- src/SFA.DAS.AssessorService.Database/StoredProcedures/StaffReports_ByStandard.sql
Note - issue TBC:
- Requirement on screeen is that there is one row per standard per version
- Requirement in Excel is that one row per standard, with versions as CSV
Current code for reports uses same SP to populate both screen and Excel
> SV-852 standard report

- src/SFA.DAS.AssessorService.Application.UnitTests/Extensions/SearchResultExtensionsTests.cs
- src/SFA.DAS.AssessorService.Application/Handlers/Search/SearchResultExtensions.cs
To prevent Index out of bounds when the previous FAIl was created by API.
> SV-1216 Fix for Record-a-grade search when previous FAIL was recorded via API

- src/SFA.DAS.AssessorService.Database/StoredProcedures/PopulateLearner.sql
- src/SFA.DAS.AssessorService.Database/Tables/ApprovalsExtract.sql
- src/SFA.DAS.AssessorService.Database/Tables/Ilrs.sql
- src/SFA.DAS.AssessorService.Database/Tables/Learner.sql
Revised approach, without the TRANSACTIOn in PopulateLearner, and with added computed LastUpdated columns on Approvals Extracrt and Ilrs, to allow only recently changed learners to be re-populated in Learner table.
> SV-1259 improve populate learner redone

- src/SFA.DAS.AssessorService.Database/PostDeploymentScripts/LookupData/StaffReportsInsertOrUpdate.sql
- src/SFA.DAS.AssessorService.Database/SFA.DAS.AssessorService.Database.sqlproj
- src/SFA.DAS.AssessorService.Database/StoredProcedures/OppFinder_List_Approved_Standards.sql
- src/SFA.DAS.AssessorService.Database/StoredProcedures/OppFinder_Update_StandardSummary.sql
- src/SFA.DAS.AssessorService.Database/StoredProcedures/StaffReports_List_Approved_Standards.sql
This change allows the **Active Apprentices by Standard with EPAOs data** to be downloaded as a report without the Exclusions that are applied to the EPAO Opportunity public view of the data. Requires that the StandardSummary data is not filtered for pre-defined Exclusions, but instead the filtering is applied on displaying the standards data in EPAO Opprtunity Finder. New staff report added to Admin service to allow the data to be downloaded without any Exclusions.
> Qf 588 move exclusions filter

- src/SFA.DAS.AssessorService.Database/StoredProcedures/PopulateLearner.sql
This allows the time periods for PopulateLearner to be parameters, to override the default values.
> QF-592 Allow PopulateLearner Stored Procedure to be parameterised 

- src/SFA.DAS.AssessorService.Application.Api.External.UnitTests/SFA.DAS.AssessorService.Application.Api.External.UnitTests.csproj
- src/SFA.DAS.AssessorService.Application.Api.External/SFA.DAS.AssessorService.Application.Api.External.csproj
- src/SFA.DAS.AssessorService.Application.Api.UnitTests/SFA.DAS.AssessorService.Application.Api.UnitTests.csproj
- src/SFA.DAS.AssessorService.Application.Api/SFA.DAS.AssessorService.Application.Api.csproj
- src/SFA.DAS.AssessorService.Application.IntegrationTests/SFA.DAS.AssessorService.Application.Api.IntegrationTests.csproj
- src/SFA.DAS.AssessorService.Application.UnitTests/SFA.DAS.AssessorService.Application.UnitTests.csproj
- src/SFA.DAS.AssessorService.Data.IntegrationTests/SFA.DAS.AssessorService.Data.IntegrationTests.csproj
- src/SFA.DAS.AssessorService.Data.UnitTests/SFA.DAS.AssessorService.Data.UnitTests.csproj
- src/SFA.DAS.AssessorService.Domain.UnitTests/SFA.DAS.AssessorService.Domain.UnitTests.csproj
- src/SFA.DAS.AssessorService.Web.UnitTests/SFA.DAS.AssessorService.Web.UnitTests.csproj
- src/SFA.DAS.AssessorService.Web/wwwroot/javascripts/address-lookup-service.js
- Encode HTML in the Address fields before showing it in the preview 
- Removed the System.ServiceModel.Federation floating package version that was added by Visual Studio while upgrading the Connected Services during the .NET 6 package. This version mismatch was preventing the master branch from building
- Updated internal SFA.DAS package references to the latest versions
- Updated package references related to unit testing
> QF-1202 Prevent XSS vulnerability in address preview by encoding HTML

- src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/UserManagement/WhenHandlingApproveContact.cs
- src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/UserManagement/WhenHandlingInviteContactToOrganisation.cs
- src/SFA.DAS.AssessorService.Application/Handlers/UserManagement/ApproveContactHandler.cs
- src/SFA.DAS.AssessorService.Application/Handlers/UserManagement/InviteContactToOrganisationHandler.cs
- src/SFA.DAS.AssessorService.Settings/ApiConfiguration.cs
- src/SFA.DAS.AssessorService.Settings/EmailTemplatesConfig.cs
- src/SFA.DAS.AssessorService.Settings/IApiConfiguration.cs
Commit Details:
Removed the LoginService from Sending email when a Contact is invited. Instead used the in-service Email Handler for sending Email notification.
Story: https://skillsfundingagency.atlassian.net/browse/FAI-987
`AS AN EPAO user
I WANT to aware of needed a [GOV.uk](http://gov.uk/) One Log in account before I join an existing Assessment service account
SO THAT I will be expecting that as part of that journey`
> FAI-760 FAI-987 New Email template for User Login SignUp
