- src/SFA.DAS.AssessorService.Application.Api.Client/TokenService.cs
- src/SFA.DAS.AssessorService.EpaoImporter/EpaoImporterFunction.cs
- src/SFA.DAS.AssessorService.EpaoImporter/Settings/ApiAuthentication.cs
- src/SFA.DAS.AssessorService.EpaoImporter/Settings/ClientApiAuthentication.cs
- src/SFA.DAS.AssessorService.EpaoImporter/Settings/IApiAuthentication.cs
- src/SFA.DAS.AssessorService.EpaoImporter/Settings/IClientApiAuthentication.cs
Small change as Domain and TenantId are essentially the same with Domain being human readable.
> Removed Domain setting and consolidated into TenantId

- src/SFA.DAS.AssessorService.Application.Api.UnitTests/WebAPI/Contacts/Maintenence/Delete/Repository/WhenDeleteContactPersistsData.cs
- src/SFA.DAS.AssessorService.Application.Api.UnitTests/WebAPI/Contacts/Maintenence/Delete/Repository/WhenDeletePersistsDataAndIsNotFound.cs
- src/SFA.DAS.AssessorService.Application.Api/SFA.DAS.AssessorService.Application.Api.csproj
Small refactor tidy up to close off ticket
> On 188 rewrite unit tests

- src/SFA.DAS.AssessorService.Application.Api/Startup.cs
- src/SFA.DAS.AssessorService.Application.Api/nlog.config
- src/SFA.DAS.AssessorService.EpaoImporter/EpaoImporterFunction.cs
- src/SFA.DAS.AssessorService.Web/Startup.cs
- src/SFA.DAS.AssessorService.Web/nlog.config
Updated nlog config to differentiate between ui and api logs
> Updated Storage connection string key. 

- src/SFA.DAS.AssessorService.Application.Api/SFA.DAS.AssessorService.Application.Api.csproj
- src/SFA.DAS.AssessorService.Application.Api/appsettings.Development.json
- src/SFA.DAS.AssessorService.Application.Api/appsettings.json
- src/SFA.DAS.AssessorService.EpaoImporter/EpaoImporterFunction.cs
- src/SFA.DAS.AssessorService.EpaoImporter/SFA.DAS.AssessorService.EpaoImporter.csproj
- src/SFA.DAS.AssessorService.EpaoImporter/local.settings.json
- src/SFA.DAS.AssessorService.EpaoImporter/nlog.config
- src/SFA.DAS.AssessorService.Web/appsettings.Development.json
- src/SFA.DAS.AssessorService.Web/appsettings.json
Added NLog to the Functions project and then shed-loads of logging statements.
> Function logging

- src/SFA.DAS.AssessorService.Application.Api.Specflow.Tests/Contacts/Maintenance/ContactMaintenance.feature
- src/SFA.DAS.AssessorService.Application.Api.Specflow.Tests/Contacts/Maintenance/ContactMaintenance.feature.cs
- src/SFA.DAS.AssessorService.Application.Api/Resources/Validators/UpdateContactRequestValidator.resx
- src/SFA.DAS.AssessorService.Application.Api/Validators/UpdateContactRequestValidator.cs
Fix to Update Contact Update Validator to display correct error messages
> Invalid const fixes and Context for Contact does not exists fixed.

- src/SFA.DAS.AssessorService.Data/AssessorDBContextFactory.cs
- src/SFA.DAS.AssessorService.Data/Migrations/20180307103749_CertificateChange.Designer.cs
- src/SFA.DAS.AssessorService.Data/Migrations/20180307103749_CertificateChange.cs
- src/SFA.DAS.AssessorService.Data/TestData/TestDataService.cs
- src/SFA.DAS.AssessorService.Database/Tables/CertificateLogs.sql
- src/SFA.DAS.AssessorService.Database/Tables/Certificates.sql
- src/SFA.DAS.AssessorService.Domain/Entities/Certificate.cs
- src/SFA.DAS.AssessorService.Domain/Entities/CertificateLog.cs
> On 208 incorrect response for put

- src/SFA.DAS.AssessorService.Data/TestData/TestDataService.cs
- src/SFA.DAS.AssessorService.Database/Tables/Organisations.sql
...and changed the ukprn in the test data.
> Updated PrimaryContact in Organisations to be Nullable

- src/SFA.DAS.AssessorService.Application.Api/StartupConfiguration/Startup.cs
- src/SFA.DAS.AssessorService.Web/Startup.cs
Whoever sees this first, can you approve and drop me a message on slack please that it's done? :)
> Lots of logging

- src/SFA.DAS.AssessorService.Application.Api.Client/Clients/ApiClientBase.cs
- src/SFA.DAS.AssessorService.Application.Api.Client/Clients/ContactsApiClient.cs
- src/SFA.DAS.AssessorService.Application.Api.Client/Clients/OrganisationsApiClient.cs
- src/SFA.DAS.AssessorService.Application.Api.Client/Clients/RegisterImportApiClient.cs
- src/SFA.DAS.AssessorService.Application.Api.Client/Clients/SearchApiClient.cs
- src/SFA.DAS.AssessorService.Application.Api.Client/SFA.DAS.AssessorService.Application.Api.Client.csproj
- src/SFA.DAS.AssessorService.Web.UnitTests/AccountControllerTests/Given_I_have_signed_in.cs
- src/SFA.DAS.AssessorService.Web.UnitTests/AccountControllerTests/Given_I_request_Sign_In.cs
- src/SFA.DAS.AssessorService.Web.UnitTests/OrchestratorTests/LoginOrchestrator/LoginOrchestratorTestBase.cs
- src/SFA.DAS.AssessorService.Web/Controllers/AccountController.cs
- src/SFA.DAS.AssessorService.Web/Orchestrators/LoginOrchestrator.cs
Changed logging to info and more of it. Desperately trying to get an insight into what's going on.
> Release debugging

- src/SFA.DAS.AssessorService.Application.Api.UnitTests/WebAPI/Contacts/Maintenence/Post/Validators/WhenCreateContactRequestValidatorFails.cs
- src/SFA.DAS.AssessorService.Application.Api.UnitTests/WebAPI/Contacts/Maintenence/Post/Validators/WhenCreateContactRequestValidatorFailsOnInvalidFieldLengths.cs
- src/SFA.DAS.AssessorService.Application.Api.UnitTests/WebAPI/Contacts/Maintenence/Put/Validators/WhenUpdateContactRequestValidatorFailsOnInvalidFieldLengths.cs
- src/SFA.DAS.AssessorService.Application.Api/Validators/CreateContactRequestValidator.cs
- src/SFA.DAS.AssessorService.Database/Tables/Contacts.sql
...temporarily until we find out if real idams will return it in claim.
> Removing email required rule

- src/SFA.DAS.AssessorService.Application.Api.Specflow.Tests/ApiStepDefinitionBase.cs
Small change to remove specflow convenience backup for now.
> On 218 to be discussed

- src/SFA.DAS.AssessorService.Application.Api.Specflow.Tests/ApiStepDefinitionBase.cs
- src/SFA.DAS.AssessorService.Application.Api.Specflow.Tests/Contacts/Maintenance/WhenCreateContact.cs
- src/SFA.DAS.AssessorService.Application.Api.Specflow.Tests/Contacts/Maintenance/WhenUpdateContact.cs
- src/SFA.DAS.AssessorService.Application.Api.Specflow.Tests/DatabaseUtils/ContactData.cs
- src/SFA.DAS.AssessorService.Application.Api.Specflow.Tests/DatabaseUtils/OrganisationData.cs
- src/SFA.DAS.AssessorService.Application.Api.Specflow.Tests/Iniltialisation.cs
- src/SFA.DAS.AssessorService.Application.Api.Specflow.Tests/Organisations/Helpers/CreateOrganisationRequestBuilder.cs
- src/SFA.DAS.AssessorService.Application.Api.Specflow.Tests/Organisations/Helpers/UpdateOrganisationBuilder.cs
- src/SFA.DAS.AssessorService.Application.Api.Specflow.Tests/Organisations/Maintenance/OrganisationMaintenance.feature
- src/SFA.DAS.AssessorService.Application.Api.Specflow.Tests/Organisations/Maintenance/OrganisationMaintenance.feature.cs
- src/SFA.DAS.AssessorService.Application.Api.Specflow.Tests/Organisations/Maintenance/WhenCreateOrganisation.cs
- src/SFA.DAS.AssessorService.Application.Api.Specflow.Tests/Organisations/Maintenance/WhenDeleteOrganisation.cs
- src/SFA.DAS.AssessorService.Application.Api.Specflow.Tests/Organisations/Maintenance/WhenUpdateOrganisation.cs
- src/SFA.DAS.AssessorService.Application.Api.Specflow.Tests/Organisations/Query/OrganisationQuery.feature
- src/SFA.DAS.AssessorService.Application.Api.Specflow.Tests/Organisations/Query/OrganisationQuery.feature.cs
- src/SFA.DAS.AssessorService.Application.Api.Specflow.Tests/Organisations/Query/WhenRetrieveAllOrganisations.cs
- src/SFA.DAS.AssessorService.Application.Api.Specflow.Tests/Organisations/Query/WhenSearchOrganisationByUkprn.cs
- src/SFA.DAS.AssessorService.Application.Api.Specflow.Tests/SFA.DAS.AssessorService.Application.Api.Specflow.Tests.csproj
- src/SFA.DAS.AssessorService.Application.Api.Specflow.Tests/packages.config
- src/SFA.DAS.AssessorService.Application.Api.UnitTests/WebAPI/Organisations/Maintenence/Post/Handlers/WhenCreateOrganisationHandlerSucceeds.cs
- src/SFA.DAS.AssessorService.Application.Api.UnitTests/WebAPI/Organisations/Maintenence/Post/Handlers/WhenDeletedOrganisationExists.cs
- src/SFA.DAS.AssessorService.Application/Handlers/OrganisationHandlers/CreateOrganisationHandler.cs
- src/SFA.DAS.AssessorService.Application/Interfaces/IContactRepository.cs
- src/SFA.DAS.AssessorService.Data/ContactRepository.cs
- src/SFA.DAS.AssessorService.Database/Tables/Contacts.sql
- src/SFA.DAS.AssessorService.Domain/Entities/Contact.cs
Dave I am assuming we are just working with master branch now. This pr relates to making the specflow tests stateless. The Organisation Tests will work, but at this point the Contact Tests are broken. Will work on those tommorow morning.
> On 254 make tests staleless

- src/SFA.DAS.AssessorService.Web/Views/Search/Results.cshtml
> Remove class on search again link

- src/SFA.DAS.AssessorService.EpaoImporter/SFA.DAS.AssessorService.EpaoImporter.csproj
> Change function to framework version

- src/SFA.DAS.AssessorService.Api.Types/Models/CreateOrganisationRequest.cs
- src/SFA.DAS.AssessorService.Application.Api.Specflow.Tests/Contacts/Maintenance/WhenCreateContact.cs
- src/SFA.DAS.AssessorService.Application.Api.Specflow.Tests/Contacts/Maintenance/WhenDeleteContact.cs
- src/SFA.DAS.AssessorService.Application.Api.Specflow.Tests/Contacts/Maintenance/WhenUpdateContact.cs
- src/SFA.DAS.AssessorService.Application.Api.Specflow.Tests/Organisations/Helpers/CreateOrganisationRequestBuilder.cs
- src/SFA.DAS.AssessorService.Application.Api.UnitTests/Validators/Organisations/Create/WhenCreateOrganisationValidatorFails.cs
- src/SFA.DAS.AssessorService.Application.Api.UnitTests/Validators/Organisations/Create/WhenCreateOrganisationValidatorFailsWithInvalidFIeldLengths.cs
- src/SFA.DAS.AssessorService.Application.Api.UnitTests/Validators/Organisations/Create/WhenCreateOrganisationValidatorSucceeds.cs
- src/SFA.DAS.AssessorService.Application.Api/Validators/CreateOrganisationRequestValidator.cs
- src/SFA.DAS.AssessorService.Application/Handlers/OrganisationHandlers/CreateOrganisationHandler.cs
Bug fix to remove Primary Contact from CreateOrganisationRequest view model, as cannot create a contact before an Organisation Created.
> Fix for bug ON_301

- src/SFA.DAS.AssessorService.Functions/Logger/AggregateLogger.cs
- src/SFA.DAS.AssessorService.Functions/SFA.DAS.AssessorService.Functions.csproj
- src/SFA.DAS.AssessorService.Functions/epaoimporter.nlog.config
- src/SFA.DAS.AssessorService.Functions/local.settings.json
- src/SFA.DAS.AssessorService.Functions/printing.nlog.config
> On 397 discriminate logs

- src/SFA.DAS.AssessorService.Application/Handlers/Certificates/StartCertificateHandler.cs
- src/SFA.DAS.AssessorService.Database/SFA.DAS.AssessorService.Database.refactorlog
- src/SFA.DAS.AssessorService.Database/Tables/Ilrs.sql
- src/SFA.DAS.AssessorService.Domain/Entities/Ilr.cs
- src/SFA.DAS.AssessorService.Web/StartupConfiguration/AuthenticationStartup.cs
Also some tidying and start of Commitments API code.
> Added Index and new Field to Ilrs

- src/SFA.DAS.AssessorService.Web/Views/Shared/_Layout.cshtml
As I haven't been able to run the solution, when this is merged please check the console for any js errors. Thanks 👍
> Added tracking script to run on non-dev environments

- src/SFA.DAS.AssessorService.Web/Views/Search/_SearchForm.cshtml
Check me out with my front end skillz.
> Removed browser autocomplete from search fields

- src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Certificates/StartCertificateHandlerTests/When_called_and_no_existing_certificate.cs
- src/SFA.DAS.AssessorService.Application/Handlers/Certificates/StartCertificateHandler.cs
- src/SFA.DAS.AssessorService.Domain/JsonData/CertificateData.cs
- src/SFA.DAS.AssessorService.ExternalApis/AssessmentOrgs/AssessmentOrgsApiClient.cs
- src/SFA.DAS.AssessorService.ExternalApis/AssessmentOrgs/IAssessmentOrgsApiClient.cs
- src/SFA.DAS.AssessorService.ExternalApis/AssessmentOrgs/Types/Provider.cs
Provider Name is now looked up and added to certificateData when Cert created
> On 664 store provider name on certificate data

- azure/parameters.json
- azure/template.json
Added:
* Management App Service
* External Api App Service
> Add two new app services to environment

- src/SFA.DAS.AssessorService.Web.Staff/Infrastructure/ApiClient.cs
- src/SFA.DAS.AssessorService.Web.Staff/SFA.DAS.AssessorService.Web.Staff.csproj
- src/SFA.DAS.AssessorService.Web.Staff/Startup.cs
Realised I'd forgotten about having to auth with Azure AD to speak to the API!  This fixes that.
> Added StructureMap and API auth

- src/SFA.DAS.AssessorService.Api.Types/Models/LearnerDetail.cs
- src/SFA.DAS.AssessorService.Application/Handlers/Staff/LearnerDetailHandler.cs
> Fixed bug with displaying learner info

- src/SFA.DAS.AssessorService.Api.Types/Models/Register/CreateEpaOrganisationRequest.cs
- src/SFA.DAS.AssessorService.Application.Api.UnitTests/Controllers/Register/Command/CreateNewOrganisationAlreadyExistsTests.cs
- src/SFA.DAS.AssessorService.Application.Api.UnitTests/Controllers/Register/Command/CreateNewOrganisationHasInvalidDataTests.cs
- src/SFA.DAS.AssessorService.Application.Api.UnitTests/Controllers/Register/Command/CreateNewOrganisationTests.cs
- src/SFA.DAS.AssessorService.Application.Api.UnitTests/Services/EpaOrganisationIdGeneratorTests.cs
- src/SFA.DAS.AssessorService.Application.Api/Controllers/RegisterController.cs
- src/SFA.DAS.AssessorService.Application.Api/Services/EpaOrganisationIdGenerator.cs
- src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Register/Command/RegisterCreateOrganisationHandlerTests.cs
- src/SFA.DAS.AssessorService.Application/Handlers/EpaOrganisationHandlers/CreateEpaOrganisationHandler.cs
- src/SFA.DAS.AssessorService.Application/Interfaces/IEpaOrganisationIdGenerator.cs
- src/SFA.DAS.AssessorService.Application/Interfaces/IRegisterQueryRepository.cs
- src/SFA.DAS.AssessorService.Data.IntegrationTests/EpaOrganisationPostTests.cs
- src/SFA.DAS.AssessorService.Data/RegisterQueryRepository.cs
Supplementary work on ON-803 to generate the organisation id rather than insert it
> On 803b updating to self generate organisation

- src/SFA.DAS.AssessorService.Database/Tables/Certificates.sql
This will fix releases following the hotfix.
> On 882 Table definition.

- src/SFA.DAS.AssessorService.Application/Interfaces/IAssessmentOrgsRepository.cs
- src/SFA.DAS.AssessorService.Data/AssessmentOrgsImporter.cs
- src/SFA.DAS.AssessorService.Data/AssessmentOrgsRepository.cs
- src/SFA.DAS.AssessorService.Data/AssessmentOrgsSpreadsheetReader.cs
- src/SFA.DAS.AssessorService.Database/Tables/OrganisationStandard.sql
- src/SFA.DAS.AssessorService.Domain/Entities/AssessmentOrganisations/EpaOrganisationStandard.cs
- src/SFA.DAS.AssessorService.Domain/Entities/AssessmentOrganisations/OrganisationContact.cs
I wanted the code change to be distinct so this is comparing the changes I've made with the original import code - basically, I had to add and populate a new field (ContactId) to OrganisationStandard table.  If you guys approve it, I'll actually merge this back into ON-668 and then it can go forward with testing. Ta.
> ON-668b changes so far

- src/SFA.DAS.AssessorService.Api.Types/Models/EpaOrganisationResponse.cs
- src/SFA.DAS.AssessorService.Application.Api.UnitTests/Controllers/Register/Command/CreateNewOrganisationAlreadyExistsTests.cs
- src/SFA.DAS.AssessorService.Application.Api.UnitTests/Controllers/Register/Command/CreateNewOrganisationHasInvalidDataTests.cs
- src/SFA.DAS.AssessorService.Application.Api.UnitTests/Controllers/Register/Command/CreateNewOrganisationTests.cs
- src/SFA.DAS.AssessorService.Application.Api.UnitTests/Controllers/Register/Command/UpdateOrganisationHasInvalidDataTests.cs
- src/SFA.DAS.AssessorService.Application.Api.UnitTests/Controllers/Register/Command/UpdateOrganisationNotFoundTests.cs
- src/SFA.DAS.AssessorService.Application.Api.UnitTests/Controllers/Register/Command/UpdateOrganisationTests.cs
- src/SFA.DAS.AssessorService.Application.Api/Controllers/RegisterController.cs
- src/SFA.DAS.AssessorService.Application.Api/StartupConfiguration/MappingStartup.cs
This is an update based on an observation that Alan noticed the ON-804 end point was a string.  Updated to be an object now. It is in effect fixing the problem for both ON-803 and ON-804
> On 804b updated response to json

- src/SFA.DAS.AssessorService.Database/Tables/Certificates.sql
Adding this here so that, once merged, active branches can pull it in and no longer have trouble releasing.
> Adding PF column to Certificates

- src/SFA.DAS.AssessorService.Application.Api.UnitTests/Services/SpecialCharacterCleanserServiceTests.cs
- src/SFA.DAS.AssessorService.Application.Api/Services/SpecialCharacterCleanserService.cs
- src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Register/Command/RegisterCreateOrganisationHandlerTests.cs
- src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Register/Command/RegisterCreateOrganisationStandardHandlerTests.cs
- src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Register/Command/RegisterUpdateOrganisationHandlerTests.cs
- src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Register/Command/RegisterUpdateOrganisationStandardHandlerTests.cs
- src/SFA.DAS.AssessorService.Application/Handlers/EpaOrganisationHandlers/CreateEpaOrganisationHandler.cs
- src/SFA.DAS.AssessorService.Application/Handlers/EpaOrganisationHandlers/CreateEpaOrganisationStandardHandler.cs
- src/SFA.DAS.AssessorService.Application/Handlers/EpaOrganisationHandlers/UpdateEpaOrganisationHandler.cs
- src/SFA.DAS.AssessorService.Application/Handlers/EpaOrganisationHandlers/UpdateEpaOrganisationStandardHandler.cs
I've requested a TR against ON-806 as I want these tested together, but didn't want to give you guys two lots of code mixed up to review.
I'm particularly keen if anyone has comments about any extra special characters to add in the 'SpecialCharacterCleanserService.cs'
Ta
> On 938 cleanse data on register end point parameters

- src/SFA.DAS.AssessorService.Web.Staff/Controllers/RegisterController.cs
- src/SFA.DAS.AssessorService.Web.Staff/Infrastructure/ApiClient.cs
- src/SFA.DAS.AssessorService.Web.Staff/Views/Register/ImPage.cshtml
Dirty, dirty code to add a page to be able to 1mp0rt organisation details from a spreadsheet (to call the patch endpoint that runs this).  Please just wave through, it's too painful to look at.
> ON-970 added code and page to run import

- src/SFA.DAS.AssessorService.Data/AssessmentOrgsRepository.cs
Everyone but Dave, please ignore!   
Dave, can we merge this ASAP.
> HOTFIX_importorgs fix now in for edge case

- src/SFA.DAS.AssessorService.Data/RegisterQueryRepository.cs
fix to deal with duplicates.  QuerySingleOrDefault does not act the same as FirstOrDefault :(
> ON-1086b fix to deal with duplicates

- src/SFA.DAS.AssessorService.Api.Types/Models/AO/EpaOrganisationStandard.cs
- src/SFA.DAS.AssessorService.Api.Types/Models/AO/OrganisationStandardData.cs
- src/SFA.DAS.AssessorService.Api.Types/Models/AO/OrganisationStandardSummary.cs
- src/SFA.DAS.AssessorService.Application/Interfaces/IAssessmentOrgsSpreadsheetReader.cs
- src/SFA.DAS.AssessorService.Data/AssessmentOrgsImporter.cs
- src/SFA.DAS.AssessorService.Data/AssessmentOrgsRepository.cs
- src/SFA.DAS.AssessorService.Data/AssessmentOrgsSpreadsheetReader.cs
- src/SFA.DAS.AssessorService.Data/DapperTypeHandlers/OrganisationStandardDataHandler.cs
- src/SFA.DAS.AssessorService.Data/RegisterQueryRepository.cs
- src/SFA.DAS.AssessorService.Data/RegisterRepository.cs
- src/SFA.DAS.AssessorService.Database/Tables/OrganisationStandard.sql
- src/SFA.DAS.AssessorService.Domain/Entities/AssessmentOrganisations/EpaOrganisation.cs
- src/SFA.DAS.AssessorService.Domain/Entities/AssessmentOrganisations/EpaOrganisationStandard.cs
- src/SFA.DAS.AssessorService.Domain/Entities/AssessmentOrganisations/OrganisationStandardData.cs
Hi chaps, added some extra logging to import, and added a new required field onto OrganisationStandard (OrganisationStandardData).
> On 1089 fix assessment orgs import

- src/SFA.DAS.AssessorService.Api.Types/Models/AO/AssessmentOrganisationSummary.cs
- src/SFA.DAS.AssessorService.Data/RegisterQueryRepository.cs
Apply Service needs to alert the primary contact of the organisation. Thus we need to expose email when searching the EPAO Register.
> ON-1126 - Added Primary Contact email on EPAO Register - Search Organisation

- src/SFA.DAS.AssessorService.Application.Api.External/Infrastructure/SandboxApiClient.cs
- src/SFA.DAS.AssessorService.Application.Api.External/Startup.cs
- src/SFA.DAS.AssessorService.Application.Api.External/SwaggerHelpers/Examples/BatchCertificateResponseExample.cs
- src/SFA.DAS.AssessorService.Application.Api.External/SwaggerHelpers/Examples/CertificateExample.cs
- src/SFA.DAS.AssessorService.Application.Api.External/SwaggerHelpers/Examples/CreateCertificateExample.cs
- src/SFA.DAS.AssessorService.Application.Api.External/SwaggerHelpers/Examples/SubmitBatchCertificateResponseExample.cs
- src/SFA.DAS.AssessorService.Application.Api.External/SwaggerHelpers/Examples/UpdateCertificateExample.cs
- src/SFA.DAS.AssessorService.Web/StartupConfiguration/AuthenticationStartup.cs
This is collection of small fixes that needed to done to the external API post release
> On 378 external api fixes postrelease

- src/SFA.DAS.AssessorService.Api.Types/Models/Azure/AzureSubscription.cs
- src/SFA.DAS.AssessorService.Api.Types/Models/Azure/AzureUser.cs
- src/SFA.DAS.AssessorService.Application.Api.Client/Azure/AzureApiClient.cs
- src/SFA.DAS.AssessorService.Application.Api.Client/Azure/IAzureApiClient.cs
- src/SFA.DAS.AssessorService.Application/Handlers/Certificates/Batch/DeleteBatchCertificateHandler.cs
- src/SFA.DAS.AssessorService.Application/Handlers/Certificates/Batch/UpdateBatchCertificateHandler.cs
- src/SFA.DAS.AssessorService.Domain/Consts/CertificateActions.cs
- src/SFA.DAS.AssessorService.Web.Staff/Startup.cs
- src/SFA.DAS.AssessorService.Web.Staff/Views/ExternalApi/UserDetails.cshtml
- src/SFA.DAS.AssessorService.Web/Controllers/ExternalApiController.cs
- src/SFA.DAS.AssessorService.Web/Startup.cs
- src/SFA.DAS.AssessorService.Web/ViewModels/ExternalApi/ExternalApiDetailsViewModel.cs
- src/SFA.DAS.AssessorService.Web/Views/ExternalApi/Index.cshtml
Allowed signup
Tidied up Dependency Injection
Tighter control on enabling/disabling user subscriptions
> ON-1229 - Fixed sign-up issue if subscribed to other APIs

- src/SFA.DAS.AssessorService.Web.Staff/wwwroot/js/epao-validation.js
Bug fix for numeric keypad not working on add/edit organisation company number field
> ON-1453 fix for numeric keypad not working on add/edit organisation

- src/SFA.DAS.AssessorService.Web.Staff/Views/Apply/Applications/MidpointApplications.cshtml
- src/SFA.DAS.AssessorService.Web.Staff/Views/Apply/Applications/StandardApplications.cshtml
- src/SFA.DAS.AssessorService.Web.Staff/Views/Apply/Financial/Dashboard.cshtml
Please ignore.  This is a copy of ON-1481 but GIT ain't playing nice.
> ON-1481b added back links

- src/SFA.DAS.AssessorService.Application.Api.Client/Clients/CertificateApiClient.cs
- src/SFA.DAS.AssessorService.Application.Api.Client/Clients/ICertificateApiClient.cs
- src/SFA.DAS.AssessorService.Application.Api.Client/Clients/IStandardsApiClient.cs
- src/SFA.DAS.AssessorService.Application.Api.Client/Clients/StandardsApiClient.cs
- src/SFA.DAS.AssessorService.Database/Script.PostDeployment1.sql
- src/SFA.DAS.AssessorService.Database/Tables/Ilrs.sql
- src/SFA.DAS.AssessorService.Web/Controllers/DashboardController.cs
Quick hotfix to stop the app erroring when a timeout occurs when getting the dashboard counts
> EPAO Dashboard Count Timeout Errors

- src/SFA.DAS.AssessorService.Data/TestData/TestDataService.cs
and AT user Ids on Contacts.
Basically, this will allow you to go from empty database to a database that will allow you to sign in through AT Login.
> Updated testdata generator with some new fields 

- src/SFA.DAS.AssessorService.Web.UnitTests/ManageUsersTests/InviteUserControllerTests/When_Invite_is_called.cs
- src/SFA.DAS.AssessorService.Web.UnitTests/ManageUsersTests/ManagerUsersControllerTests/When_User_is_called.cs
- src/SFA.DAS.AssessorService.Web/Controllers/ManageUsers/InviteUserController.cs
- src/SFA.DAS.AssessorService.Web/Controllers/ManageUsers/ManageUsersController.cs
- src/SFA.DAS.AssessorService.Web/Controllers/ManageUsers/UserDetailsController.cs
- src/SFA.DAS.AssessorService.Web/Views/ManageUsers/Index.cshtml
Change user name to link to a (currently non-existant) User details page.
Added button to (currently non-existant) Invite User page
> ON-1848 Changes to Manage Users page

- src/SFA.DAS.AssessorService.Web.Staff/Controllers/Roatp/AddRoatpOrganisationController.cs
This is a minor temporary fix, as all this kind of flow is reworked in the UKRLP sub-branch.
> APR-469 bug fixed

- src/SFA.DAS.AssessorService.Application.Api/Consts/EpaOrganisationValidatorMessageName.cs
- src/SFA.DAS.AssessorService.Application.Api/Resources/Validators/EpaOrganisationValidator.en.resx
- src/SFA.DAS.AssessorService.Application.Api/Validators/EpaOrganisationValidator.cs
- src/SFA.DAS.AssessorService.Application/Interfaces/IEpaOrganisationValidator.cs
- src/SFA.DAS.AssessorService.Web.Staff/Views/Register/EditOrganisation.cshtml
The ukprn is required for making an organisation live or editing an already live organisation.
> ON-1789 The ukprn is required for a live organisation

- src/SFA.DAS.AssessorService.Application.Api.Client/Clients/OrganisationsApiClient.cs
- src/SFA.DAS.AssessorService.Web.UnitTests/ManageUsersTests/UserDetailsControllerTests/UserDetailsControllerTestsBase.cs
- src/SFA.DAS.AssessorService.Web/Controllers/ManageUsers/UserDetailsController.cs
- src/SFA.DAS.AssessorService.Web/Controllers/ManageUsers/ViewModels/UserRemovedViewModel.cs
- src/SFA.DAS.AssessorService.Web/Views/ManageUsers/UserDetails/Removed.cshtml
Extra PR for a missing User Removed screen.  UI work still yet to be carried out.... as you can tell. 😆
> On 1862 Add extra User Removed screen

- src/SFA.DAS.AssessorService.Application.Api/Validators/EpaOrganisationValidator.cs
- src/SFA.DAS.AssessorService.Application/Interfaces/IEpaOrganisationValidator.cs
- src/SFA.DAS.AssessorService.Application/Interfaces/IRegisterValidationRepository.cs
- src/SFA.DAS.AssessorService.Data/RegisterValidationRepository.cs
- src/SFA.DAS.AssessorService.Web/Resources/Validators/CertificateCheckViewModelValidator.Designer.cs
Error When Adding A New Contact To An Organisation When Contact Status is Applying and New
> ON-1960 Error When Adding A New Contact To An Organisation

- azure/sandbox-template.json
This PR adds the UseSandboxServices app setting to the internalApiSandboxAppServiceName web app deployment with a value of yes.
> Added UseSandboxServices app setting to internalApiSandboxAppServiceName

- azure/template.json
Remove/ decommission Manage Assessors deployment of `das-*-assmgt-as` from the das-assessor-service deployment pipelines.
> Remove Manage App Service from ARM

- src/SFA.DAS.AssessorService.Application/Handlers/Apply/UpdateGradeHandler.cs
The org.OrganisationData.RoEPAOApproved is legacy and was a part of the old Apply process
> ON-2272 : Always update FHA Details when Grading FHA

- azure/template.json
- Added the `deploymentUrlBase` to variable section
- Updated uri links in each linked deployment resource to use the `deploymentUrlBase` variable
- Added a Storage Account Container deployment resource in preparation for removing the PowerShell `Create Template Container` task in the das-assessor-service release pipeline as it is no longer required and will enable the removal of the ESFA.InfrastructureAutomation package.
> Added Storage Account Container deployment resource and added the deploymentUrlBase variable

- .gitignore
- README.md
- sonarcloud/Dockerfile
- sonarcloud/analyse.ps1
Adds a docker file that can build a sonarcloud environment capable of building and uploading soanrcloud analyse reports.
> Adds sonarcloud configuration and updates the readme

- src/SFA.DAS.AssessorService.Api.Types/Models/OrganisationStandardResponse.cs
- src/SFA.DAS.AssessorService.Application.Api.UnitTests/Controllers/Standards/Query/WhenGettingEPAOrganisationsByStandard.cs
- src/SFA.DAS.AssessorService.Application.Api.UnitTests/SFA.DAS.AssessorService.Application.Api.UnitTests.csproj
- src/SFA.DAS.AssessorService.Application.Api/AutoMapperProfiles/AssessorServiceOrganisationProfile.cs
- src/SFA.DAS.AssessorService.Application.Api/Controllers/StandardQueryController.cs
- src/SFA.DAS.AssessorService.Application.Api/StartupConfiguration/MappingStartup.cs
- src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Organisations/GetEpaOrganisationsByStandard/WhenGettingEpaOrganisationsByStandard.cs
- src/SFA.DAS.AssessorService.Application.UnitTests/SFA.DAS.AssessorService.Application.UnitTests.csproj
- src/SFA.DAS.AssessorService.Application/Handlers/ao/GetEpaOrganisationsByStandard/GetEpaOrganisationsByStandardQuery.cs
- src/SFA.DAS.AssessorService.Application/Handlers/ao/GetEpaOrganisationsByStandard/GetEpaOrganisationsByStandardQueryHandler.cs
- src/SFA.DAS.AssessorService.Application/Handlers/ao/GetEpaOrganisationsByStandard/GetEpaOrganisationsByStandardResponse.cs
- src/SFA.DAS.AssessorService.Application/Interfaces/IOrganisationQueryRepository.cs
- src/SFA.DAS.AssessorService.Data/AssessorDbContext.cs
- src/SFA.DAS.AssessorService.Data/OrganisationQueryRepository.cs
- src/SFA.DAS.AssessorService.Domain/Entities/DeliveryArea.cs
- src/SFA.DAS.AssessorService.Domain/Entities/Organisation.cs
- src/SFA.DAS.AssessorService.Domain/Entities/OrganisationStandard.cs
- src/SFA.DAS.AssessorService.Domain/Entities/OrganisationStandardDeliveryArea.cs
Added new action to be able to return a list of EPAOs by standard code, also returns the delivery area
> FAT2-70 Get epao by standard

- azure/sandbox-template.json
- Added parameter so we can override the runtime in the release pipeline
- Set default value to opt-out of runtime upgrade
> Update function runtime

- src/SFA.DAS.AssessorService.Api.Types/Models/OrganisationResponse.cs
- src/SFA.DAS.AssessorService.Application.Api/AutoMapperProfiles/AssessorServiceOrganisationProfile.cs
- src/SFA.DAS.AssessorService.Application.Api/StartupConfiguration/Startup.cs
Added to FAT endpoint:
- Postcode
- City/Address4
- DeliveryAreaId
> FAT2-207 find epao detail

- src/SFA.DAS.AssessorService.Database/PostDeploymentScripts/EPAO_MIgration_Part4_Apply.sql
- src/SFA.DAS.AssessorService.Database/SFA.DAS.AssessorService.Database.sqlproj
- src/SFA.DAS.AssessorService.Database/Script.PostDeployment1.sql
- src/SFA.DAS.AssessorService.Database/Tables/Apply.sql
Database changes and migration script for SV in EPAO Apply
> SV-541 migration for epao apply

- src/SFA.DAS.AssessorService.Data/Apply/ApplyRepository.cs
- src/SFA.DAS.AssessorService.Database/PostDeploymentScripts/EPAO_MIgration_Part4_Apply.sql
> Sv 541 migration for epao apply

- src/SFA.DAS.AssessorService.Api.Types/Models/Certificates/CertificateSummaryResponse.cs
- src/SFA.DAS.AssessorService.Application/Handlers/Certificates/GetCertificatesHistoryHandler.cs
- src/SFA.DAS.AssessorService.Web/Resources/Views/CertificateHistory/Index.en.resx
- src/SFA.DAS.AssessorService.Web/Views/CertificateHistory/Index.cshtml
Add's version for completed certificates for pass and fails.
It is still awaiting final content so 'Unavailable' may change
> SV-399 epao completed assessments to show standard versions against outcomes

- src/SFA.DAS.AssessorService.Web/Views/CertificateHistory/Index.cshtml
Corrects unavailable content and moves version row to below standard level.
> SV-399 version unavailable content update

- src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Certificates/StartCertificateHandlerTests/When_called_and_certificate_previously_recorded_a_fail.cs
- src/SFA.DAS.AssessorService.Application/Handlers/Staff/StartCertificateHandler.cs
- src/SFA.DAS.AssessorService.Domain/Consts/CertificateActions.cs
Updated certificate log to record Restart instead of StartRetake
> SV-720 Rename StartRetake action to Restart

- src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Certificates/StartCertificateHandlerTests/When_called_and_certificate_previously_recorded_a_fail.cs
- src/SFA.DAS.AssessorService.Application/Handlers/Staff/StartCertificateHandler.cs
> SV-715 fail to pass achievement date should not be prefilled

- azure/sandbox-template.json
- azure/template.json
- Updated to subscription deployment
- Integrated app services into subnets
- Removed deployment of sandbox function app and storage account
> Updated to subscription deployment, integrated app services into subnets, removed function app/storage account

- src/PostmanCollection/Assessor Service - External Api.postman_collection.json
- src/PostmanCollection/Assessor Service - External Api.postman_environment.json
Added postman collection with skeleton requests for the Assessor service external API
> SV-809 postman collection

- src/SFA.DAS.AssessorService.Application.Api/StartupConfiguration/MappingStartup.cs
- src/SFA.DAS.AssessorService.Application/Handlers/Apply/Review/OrganisationApplicationsHandler.cs
- src/SFA.DAS.AssessorService.Application/Handlers/Apply/Review/StandardApplicationsHandler.cs
- src/SFA.DAS.AssessorService.Application/Handlers/Apply/Review/WithdrawalApplicationsHandler.cs
- src/SFA.DAS.AssessorService.Application/Interfaces/IApplyRepository.cs
- src/SFA.DAS.AssessorService.Application/Mapping/AutoMapperProfiles/ApplicationSummaryItemProfile.cs
- src/SFA.DAS.AssessorService.Data/Apply/ApplyRepository.cs
- src/SFA.DAS.AssessorService.Domain/Entities/ApplicationListItem.cs
Creates a specific domain object to represent a row in the Apply_List_Applications stored proc which returns Versions as a Json string due to Dapper limitation. Internally maps this to a ApplicationSummaryItem which has version as a list of strings for exposure through the API.
> SV-656 standard version csv

- src/SFA.DAS.AssessorService.Data/Apply/ApplyRepository.cs
Need to clear fields used by SV in Apply on cancelling first Apply.
> SV-1041_Cancel_first_Standard

- src/SFA.DAS.AssessorService.Data/StandardRepository.cs
Was allowing users to Apply for Standards that had been withdrawn, but never had been Published.
> SV-1072_Filter_out_Unpublished_Standards

- src/SFA.DAS.AssessorService.Data/Apply/ApplyRepository.cs
- src/SFA.DAS.AssessorService.Data/RegisterQueryRepository.cs
- src/SFA.DAS.AssessorService.Database/StoredProcedures/EPAO_Registered_Standards.sql
(cherry picked from commit 66067a937442424612da665f5fd3d623871b4147)
> SV-987 soft delete

- src/SFA.DAS.AssessorService.Database/StoredProcedures/EPAO_Register_list_of_organisations.sql
... to Alphabetical rather than random
> SV-1086 correct ordering on register list of Organisations

- src/SFA.DAS.AssessorService.Data/RegisterQueryRepository.cs
- src/SFA.DAS.AssessorService.Database/StoredProcedures/EPAO_Registered_Standards.sql
To ignore Withdrawal, "Apply" records for the same StandardReference
> SV-1113 Standard Option page fix

- src/SFA.DAS.AssessorService.Database/StoredProcedures/StaffReports_ByStandard.sql
Restoring the Standard Code field to the report
> SV-1118 bug standard code missing

- src/SFA.DAS.AssessorService.Application/Handlers/OrganisationStandards/UpdateOrganisationStandardVersionHandler.cs
> SV-1136 set date approved on RoEPAO update

- src/SFA.DAS.AssessorService.Web.UnitTests/CertificateTests/CertificateControllerTests.cs
- src/SFA.DAS.AssessorService.Web/Controllers/CertificateController.cs
- src/SFA.DAS.AssessorService.Web/ViewModels/Certificate/CertificateStartViewModel.cs
- src/SFA.DAS.AssessorService.Web/Views/Search/ChooseStandard.cshtml
- src/SFA.DAS.AssessorService.Web/Views/Search/Result.cshtml
Refactor start certificate controller to better handle Learner version and option data
> SV-1264 Refactor start certificate controller

- src/SFA.DAS.AssessorService.Application.Api/Controllers/StandardVersionController.cs
Reverts SkillsFundingAgency/das-assessor-service#1367
> SV-1293-Revert "SV-1293 Fix lars code route mapping"

- src/SFA.DAS.AssessorService.Data/RegisterQueryRepository.cs
- src/SFA.DAS.AssessorService.Data/StandardRepository.cs
For API changes needed to support the Find An EPAO service with Standards Versioning.
> SV 1283 find an epao

- src/SFA.DAS.AssessorService.Web/wwwroot/javascripts/application.js
Reverts SkillsFundingAgency/das-assessor-service#1419
Reverting as it's impacting the Permission change page due to the disabled button.
> Revert "Disable submit buttons on all forms after form submission"

- src/SFA.DAS.AssessorService.Web.UnitTests/StandardControllerTests/When_OptIn_Is_Posted_To.cs
- src/SFA.DAS.AssessorService.Web/Controllers/Apply/ApplicationController.cs
- src/SFA.DAS.AssessorService.Web/Controllers/Apply/StandardController.cs
Correct validation for opt-in version application
> SV-1425 Correct validation for opt-in version application

- src/SFA.DAS.AssessorService.Data/SandboxDbRepository.cs
The Sandbox Ilrs test data uses the EPAOs UKPRN as the Training provider, which is not real but simplifies test data preparation. Not all EPAOs are also TPs so these UKPRNs need to be added to the Providers table in Sandbox to allow the External API to operate successfully.
> QF-589_add Providers table update to Step 6 generate test data

- src/SFA.DAS.AssessorService.Data/SandboxDbRepository.cs
- src/SFA.DAS.AssessorService.Database/PostDeploymentScripts/LookupData/StaffReportsInsertOrUpdate.sql
- src/SFA.DAS.AssessorService.Database/SFA.DAS.AssessorService.Database.sqlproj
- src/SFA.DAS.AssessorService.Database/StoredProcedures/OppFinder_List_Approved_Standards.sql
- src/SFA.DAS.AssessorService.Database/StoredProcedures/OppFinder_Update_StandardSummary.sql
- src/SFA.DAS.AssessorService.Database/StoredProcedures/PopulateLearner.sql
- src/SFA.DAS.AssessorService.Database/StoredProcedures/StaffReports_List_Approved_Standards.sql
> QF-605-NumerousAssessorsFixes

- src/SFA.DAS.AssessorService.Data.IntegrationTests/Services/TestWebConfiguration.cs
- src/SFA.DAS.AssessorService.Settings/IWebConfiguration.cs
- src/SFA.DAS.AssessorService.Settings/WebConfiguration.cs
- src/SFA.DAS.AssessorService.Web/Controllers/HomeController.cs
- src/SFA.DAS.AssessorService.Web/Models/HomeIndexViewModel.cs
- src/SFA.DAS.AssessorService.Web/Views/Home/Index.cshtml
Commit Details:
Updated the start page contents and removed the Create Account link from the Start Page
Story Link:
https://skillsfundingagency.atlassian.net/browse/FAI-757
> FAI-757 Update the EPAO assessment service start page for GSI

- src/SFA.DAS.AssessorService.Application.Api/Controllers/Staff/StaffReportsController.cs
- src/SFA.DAS.AssessorService.Data/Staff/StaffReportRepository.cs
Edit code to be more robust against malicious inputs when running a stored proc against the database.
> QF-1203 Resolve security issue

- src/SFA.DAS.AssessorService.Web/Views/Application/StandardApplications.cshtml
Removed the button which allows new standard applications
> QF-1461 - Turn Off New Standard Apply

- src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/UserManagement/WhenHandlingApproveContact.cs
- src/SFA.DAS.AssessorService.Application/Handlers/UserManagement/ApproveContactHandler.cs
- src/SFA.DAS.AssessorService.Settings/EmailTemplatesConfig.cs
Email Template Id comes from Config rather than from Database so that template changes based on Environment
Story:https://skillsfundingagency.atlassian.net/browse/FAI-991
> FAI-760 FAI-991 Approve User Confirmation Email Template from Config

- src/SFA.DAS.AssessorService.Api.Types/Models/UpdateEmailRequest.cs
- src/SFA.DAS.AssessorService.Application.Api.Client/Clients/ContactsApiClient.cs
- src/SFA.DAS.AssessorService.Application.Api.Client/Clients/IContactsApiClient.cs
- src/SFA.DAS.AssessorService.Application.Api.UnitTests/Controllers/Contacts/Command/WhenUpdateEmailSucceeds.cs
- src/SFA.DAS.AssessorService.Application.Api.UnitTests/Validators/Contacts/UpdateEmail/UpdateEmailRequestValidatorTestBase.cs
- src/SFA.DAS.AssessorService.Application.Api.UnitTests/Validators/Contacts/UpdateEmail/WhenUpdateEmailRequestValidatorFailsOnInvalidFieldLengths.cs
- src/SFA.DAS.AssessorService.Application.Api.UnitTests/Validators/Contacts/UpdateEmail/WhenUpdateEmailRequestValidatorSucceeds.cs
- src/SFA.DAS.AssessorService.Application.Api.UnitTests/Validators/Contacts/UpdateEmail/WhenUpdateEmailViewModelValidatorFails.cs
- src/SFA.DAS.AssessorService.Application.Api/Controllers/ContactController.cs
- src/SFA.DAS.AssessorService.Application.Api/Validators/UpdateEmailRequestValidator.cs
- src/SFA.DAS.AssessorService.Application.UnitTests/Handlers/Contacts/WhenUpdateEmailHandler.cs
- src/SFA.DAS.AssessorService.Application/Handlers/ContactHandlers/UpdateEmail/UpdateEmailHandler.cs
- src/SFA.DAS.AssessorService.Application/Interfaces/IContactRepository.cs
- src/SFA.DAS.AssessorService.Data/ContactRepository.cs
- src/SFA.DAS.AssessorService.Web.UnitTests/StartupConfiguration/AssessorServiceAccountPostAuthenticationClaimsHandlerTests.cs
- src/SFA.DAS.AssessorService.Web/StartupConfiguration/Authorization/AssessorServiceAccountPostAuthenticationClaimsHandler.cs
Update the Contact Email Address if the Email address from Gov UK Sign-In is different from Repo details
Story: https://skillsfundingagency.atlassian.net/browse/FAI-988#1555
> FAI-760 FAI-988 Update Assessment Service (EPAO) users email address after changing in Gov.uk profile

- azure/api-management/policies/apis/das-assessor-service-api-external.xml
- azure/scripts/Set-ApimApiPolicy.ps1
- pipeline-templates/job/deploy.yml
- src/SFA.DAS.AssessorService.Application.Api.Client/Configuration/AssessorExternalApiClientConfiguration.cs
- src/SFA.DAS.AssessorService.Application.Api.External/Controllers/PingController.cs
- src/SFA.DAS.AssessorService.Application.Api.External/SFA.DAS.AssessorService.Application.Api.External.csproj
- src/SFA.DAS.AssessorService.Application.Api.External/Startup.cs
- src/SFA.DAS.AssessorService.Application.Api/Controllers/PingController.cs
- src/SFA.DAS.AssessorService.Settings/ExternalApiConfiguration.cs
- src/SFA.DAS.AssessorService.Settings/IExternalApiConfiguration.cs
Updated APIM Policy
Allow anonymous access on ling endpoints
> QF-1322-External-API-Authentication

- azure/template.json
Removed the following resources for -assextapi-sbox-as:
* App Service
* App Insights 
* Certifcate
> Removed ARM template config for -assextapi-sbox-as

- src/SFA.DAS.AssessorService.Api.Types/Models/AO/UpdateAssessmentsSummaryRequest.cs
- src/SFA.DAS.AssessorService.Application.Api/Controllers/RegisterQueryController.cs
- src/SFA.DAS.AssessorService.Application/Handlers/ao/UpdateAssessmentsSummaryHandler.cs
- src/SFA.DAS.AssessorService.Data/AssessorDbContext.cs
- src/SFA.DAS.AssessorService.Data/AssessorUnitOfWork.cs
- src/SFA.DAS.AssessorService.Data/CertificateRepository.cs
- src/SFA.DAS.AssessorService.Data/Interfaces/IAssessorDbContext.cs
- src/SFA.DAS.AssessorService.Data/Interfaces/IAssessorUnitOfWork.cs
- src/SFA.DAS.AssessorService.Data/Interfaces/ICertificateRepository.cs
- src/SFA.DAS.AssessorService.Database/SFA.DAS.AssessorService.Database.sqlproj
- src/SFA.DAS.AssessorService.Database/StoredProcedures/AssessmentsSummaryUpdate.sql
- src/SFA.DAS.AssessorService.Database/Tables/AssessmentsSummary.sql
- src/SFA.DAS.AssessorService.Domain/Entities/AssessmentsSummary.cs
Adds new endpoint 
POST /api/ao/assessments/update-assessments-summary
to summarise data into **AssessmentsSummary** table using AssessmentsSummaryUpdate Stored Procedure
And updates 
GET /api/ao/assessments 
to take data from the summary table
> CSP-2057 FAT Performance for Assessment counts

- src/SFA.DAS.AssessorService.Database/Tables/Certificates.sql
Fix performance issues in reports
> P2-2598 Report performance fix
